apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: workload-service-keda
  namespace: autoscaling-experiment
  labels:
    app: workload-service
    autoscaler: predictive-keda
    app.kubernetes.io/name: workload-service-keda
    app.kubernetes.io/part-of: predictive-kubernetes-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workload-service
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 5
  cooldownPeriod: 30
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        metricName: predicted_workload_requests_per_second
        query: sum(predicted_workload_requests_per_second)
        threshold: "30"
  advanced:
    horizontalPodAutoscalerConfig:
      name: workload-service-keda-hpa
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          selectPolicy: Max
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
            - type: Pods
              value: 2
              periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 60
          selectPolicy: Min
          policies:
            - type: Percent
              value: 50
              periodSeconds: 30
            - type: Pods
              value: 1
              periodSeconds: 30
