apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: autoscaling-experiment
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: predictive-kubernetes-autoscaling
type: Opaque
stringData:
  POSTGRES_DB: autoscaling_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/autoscaling_db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
  SPRING_JPA_DIALECT: org.hibernate.dialect.PostgreSQLDialect
